### ISSUE TITLE
Instagram preview in sidebar

### ISSUE THREAD

**Issue by divmazie** [divmazie/jonathancoulton-theme#14]
WP widget? Api?

**Comment by drewwestphal** [comment]
API seems like it would probably be about as easy? IDK... why are you considering widget?

**Comment by divmazie** [comment]
I saw at least one widget that claimed to be dead simple, but if we can't style it easily, then it's not worth it. API is likely, I'm just documenting my thought process.

**Comment by drewwestphal** [comment]
Neato. Sounds good. Let me know if I should assist in some way!

**Comment by divmazie** [comment]
6c0b13e0d04121b1f8dcab3950dbf5b2f3c78499
