### ISSUE TITLE
grey out cart if no contents?

### ISSUE THREAD

**Issue by drewwestphal** [divmazie/jonathancoulton-theme#28]
easy?

**Comment by divmazie** [comment]
eb62dc4 This makes it grey, but doesn't actually disable it, which is weird because bootstrap v knockout

**Comment by drewwestphal** [comment]
I think you meant to reference 683ac3d879cd89835d1257241eeb870f458a1372 rather than the above PR merge

This should allow you to alter the bootstrap attributes: 
http://knockoutjs.com/documentation/attr-binding.html
