### ISSUE TITLE
Check that unicode chars removed in filenames

### ISSUE THREAD

**Issue by divmazie** [divmazie/jonathancoulton-theme#5]
Might need 'u' in regex

**Comment by divmazie** [comment]
Unicode chars are being converted into hex numbers, and adding u to regex doesn't seem to solve it. This might be fine though?

**Comment by drewwestphal** [comment]
Let's convert them to ASCII. Iconv should do the trick.

Also I'm having some ideas might simply Wordpress file asset if you want to
chat about them

**Comment by divmazie** [comment]
I'm an idiot, they were being deleted. I thought the shortened copy of the hash was a unicode conversion. I added iconv to convert to ascii anyway.
